# name of the software
name: Scribbler

project:
  version: 1.0.0
  download_url: https://github.com/gopi-suvanam/scribbler/archive/refs/heads/main.zip
  download_text: Download

license:
  software: MIT License
  software_url: https://github.com/gopi-suvanam/scribbler/blob/main/LICENSE

  docs: CC BY 3.0
  docs_url: https://creativecommons.org/licenses/by/3.0/

links:
  header:
    - title: GitHub
      icon: github
      brand: true
      url: https://github.com/gopi-suvanam/scribbler/
  homepage:
    - title: Try here
      icon: play
      brand: true
      url: https://app.scribble.live/
  footer:
    - title: GitHub
      icon: github
      brand: true
      url: https://github.com/gopi-suvanam/scribbler/
    - title: Issues
      icon: bug
      url: https://github.com/gopi-suvanam/scribbler/issues

ui:
  mode: 'auto' # 'auto', 'dark', 'light'
  brand:
    dark: "#0021ff"
    light: "#ffde00"
  border_color:
    dark: "#0021FF"
    light: "#ffde00"
  header:
    trianglify: true
    dark:
      color1: "#062a48"
      color2: "#304e67"
    light:
      color1: "#ff0000"
      color2: "#00de00"
  masthead:
    color:
      dark: "#ffde00"
      light: "#ffde00"
    align:
      homepage: 'center'
      page: 'left'

social:
  github:
    user: gopi-suvanam
    repo: scribbler


#analytics:
#  google: UA-123456-1

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - jekyll-docs-theme.gemspec
  - LICENSE.md
  - README.md
  - screenshot.png
